Update tests.yml

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -7,16 +7,21 @@ on:
     tags:
       - '**'
 
-jobs:
+jobs: 
   tests:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
-      - name: Check if the repository is private
-        run: exit 1
-        if: ${{github.event.repository.private}}
-      - name: Tests
+      
+      - name: Check if repository is private
+        if: github.event.repository.private
+        run: |
+          echo "Error: Private repositories are not allowed for this workflow"
+          exit 1
+      
+      - name: Run tests
+        if: github.event.repository.private != true
         uses: Yandex-Practicum/test-project-action@v1
         with:
           project: 'ono-tebe-nado-ad'
